version: '3.9'
services:
  ansible:
    container_name: ansible
    build: ./lab/controlPlane
    # If the container have daemon, "tty: true" is unnecessary. Otherwise, it is necessary.
    tty: true
    working_dir: '/var/data'
    volumes:
      - .:/var/data
  target01:
    container_name: target01
    build: ./lab/target
    tty: true
  target02:
    container_name: target02
    build:
      context: ./lab/target
      dockerfile: DockerfileUbuntu
    tty: true