-
  name: "date and time"
  gather_facts: false
  hosts: target01
  tasks:
    -
      name: "Date"
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.pipe', 'date') }}"
    -
      name: "ISO"
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.pipe', 'date +%Y-%m-%dT%H:%M:%S%z') }}"
