- # this - is needed as it indicates list of plays

  hosts: all

  vars:
    centos: "Centos rock\n"
    ubuntu: "Ubuntu rock\n"

  tasks:
    - name: "Motd message for Ubuntu"
      copy:
        content: "{{ ubuntu }}"
        dest: /etc/motd
      when: ansible_distribution == "Ubuntu" # take key from ansible setup module
    - name: "Motd message for Centos"
      copy:
        content: "{{ centos }}"
        dest: /etc/motd
      when: ansible_distribution == "Redhat"
    - name: "Motd message for Centos"
      package:
        name: tree
        state: present
      notify: Tree installed
  handlers:
    - name: Tree installed
      debug:
        msg: "Tree Installed"