-
  name: "Create Custom Facts"
  hosts: all
  tasks:
    -
      name: Create Facts.d folder
      ansible.builtin.file:
        path: "/etc/ansible/facts.d"
        state: directory
    -
      name: Copy custom.facts file
      ansible.builtin.copy:
        dest: "/etc/ansible/facts.d/custom.fact"
        src: "./custom.fact"
        mode: 0755

# After running this play run ' ansible all -m setup -a "filter=ansible_local" ' 
# this command and check custom fact