-
  name: "Inline Module"
  hosts: all
  gather_facts: true
  vars:
    file: /etc/ssh/sshd_config
  tasks:
    -
      name: "Update SSHD"
      ansible.builtin.lineinfile:
        path: "{{ file }}"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"
        state: present
        validate: "sshd -t -f %s" # %s is path of file and ansible will insert it auto
    -
      name: "Verify"
      ansible.builtin.shell: "egrep ^PasswordAuthentication {{ file }}"
