-
  name: Failed when
  hosts: target01
  gather_facts: false
  tasks:
      -
        name: List home
        ansible.builtin.command: "ls /home"
        register: home_out
        failed_when: home_out.rc == 0
      # -
      #   name: Another Way
      #   ansible.builtin.command: "ls /home"
      #   register: home_out
      # -
      #   name: Failed
      #   ansible.builtin.fail:
      #     msg: Failed to list home
      #   when: home_out.rc == 0
