-
  name: "Vars Play"
  hosts: all
  vars:
    a: 1
    b: false # or no
    c: "Abc"
  tasks:
    -
      name: "Display var type"
      ansible.builtin.debug:
        msg:
          - This is {{ a | type_debug }}
          - This is {{ b | type_debug }}
          - This is {{ c | type_debug }}
