-
  name: Read from Prompt
  hosts: target01
  gather_facts: false
  vars_prompt:
    -
      name: user
      prompt: Enter user name
      private: false
    -
      name: password
      prompt: Enter password
      private: true
  tasks:
    -
      name: Display user name and password
      ansible.builtin.debug:
        msg: "This is my user:{{ user }} and password:{{ password }}"
